# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheWall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWall.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWall.User')),
            ],
        ),
    ]
