# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWall', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='message',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.ManyToManyField(related_name='liked_messages', to='TheWall.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
