# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pword',
            field=models.CharField(max_length=255),
        ),
    ]
